astromatch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path("admin/", admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_astrology', views.get_astrology, name='get_astrology'),
    path('asthkoot_table', views.asthkoot_table, name='asthkoot_table'),
    path('match_making', views.match_making, name='match_making'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from code.astroMatch import * #MatchMaking, get_person_asthkoot_df, get_asthakoot_base_df, get_moon_info_with_asthkoot

from astromatch.settings import BASE_DIR

def export_to_html(df, addClass:list=[]):
    base_classes = ['mytable', 'table', 'table-sm']
    allClasses = base_classes + addClass
    df = df.to_html(index=False, justify='center', classes=tuple(allClasses)) #, 'table-bordered', 'table-hover'
    return df

# Create your views here.

def index(request):
    context = {}
    return render(request, 'index.html', context=context)

def asthkoot_table(request):
    context = {}
    df = get_asthakoot_base_df(filePath=BASE_DIR / 'code/Nakshatras.xlsx', changeColName=True)
    context['asthkootdf'] = export_to_html(df=df, addClass=['table-hover'])
    return render(request, 'asthakoot.html', context=context)

def get_astrology(request):
    context = {}
    
    dob, tob, tz = request.POST.get('dob'), request.POST.get('tob'), request.POST.get('timezone')
    year, month, day = [int(i) for i in dob.split('-')]
    hour, minute = [int(i) for i in tob.split(':')]
    
    dt_utc = MatchMaking().convert_standard_to_utc_time(year, month, day, hour, minute, second=0, timeZone=tz)
    moon = MatchMaking().moon(dt_utc)
    df = get_asthakoot_base_df(filePath=BASE_DIR / 'code/Nakshatras.xlsx')
    moondf = get_moon_info_with_asthkoot(df, moon, changeColName=True)
    context['moondf'] = export_to_html(df=moondf)

    return render(request, 'index.html', context=context)

def match_making(request):
    context = {}
    if request.POST:
        m_dob, m_tob, m_tz = request.POST.get('m_dob'), request.POST.get('m_tob'), request.POST.get('m_timezone')
        context['m_dob'], context['m_tob'], context['m_tz'] = m_dob, m_tob, m_tz
        year, month, day = [int(i) for i in m_dob.split('-')]
        hour, minute = [int(i) for i in m_tob.split(':')]

        dt_utc = MatchMaking().convert_standard_to_utc_time(year, month, day, hour, minute, second=0, timeZone=m_tz)
        moon = MatchMaking().moon(dt_utc)
        df = get_asthakoot_base_df(filePath=BASE_DIR / 'code/Nakshatras.xlsx')
        maledf = get_moon_info_with_asthkoot(df, moon, changeColName=True)

        context['male_moondf'] = export_to_html(df=maledf)

        f_dob, f_tob, f_tz = request.POST.get('f_dob'), request.POST.get('f_tob'), request.POST.get('f_timezone')
        context['f_dob'], context['f_tob'], context['f_tz'] = f_dob, f_tob, f_tz
        year, month, day = [int(i) for i in f_dob.split('-')]
        hour, minute = [int(i) for i in f_tob.split(':')]

        dt_utc = MatchMaking().convert_standard_to_utc_time(year, month, day, hour, minute, second=0, timeZone=f_tz)
        moon = MatchMaking().moon(dt_utc)
        
        femaledf = get_moon_info_with_asthkoot(df, moon, changeColName=True)

        context['female_moondf'] = export_to_html(df=femaledf)

        criterion_df_path = BASE_DIR / 'code/asthkoot_criterion.xlsx'
        dfM = get_matchmaking_df_v1(maledf, femaledf, criterion_df_path)
        
        matchdf_final = dfM[0].reset_index(drop=False)
        context['match_df'] = export_to_html(df=matchdf_final)

        context['total_points'] = dfM[-1]

    return render(request, 'matchmaking.html', context=context)




# def get_astrology(request):
#     response = {}
#     if request.POST.get('action') == 'post':
#         dob, tob, tz = request.POST.get('dob'), request.POST.get('tob'), request.POST.get('timezone')
#         year, month, day = [int(i) for i in dob.split('-')]
#         hour, minute = [int(i) for i in tob.split(':')]

#         dt_utc = MatchMaking().convert_standard_to_utc_time(year, month, day, hour, minute, second=0, timeZone=tz)
#         moon = MatchMaking().moon(dt_utc)
#         df = get_asthakoot_base_df(filePath=BASE_DIR / 'code/Nakshatras.xlsx')
#         moondf = get_person_asthkoot_df(df, moon.position, detailed=True)
#         moondf = moondf.to_dict(orient='records')

#         response ={ 
#             'status' : 200, 
#             'dtUTC' : dt_utc, 
#             'overview' : moon.overview, 
#             'degrees': moon.position,
#             'moondf' : moondf[0]
#         }

#     return JsonResponse(response)

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href=" {% url 'home:index' %} ">PS AstroMatch</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if 'asthkoot_table' in request.resolver_match.route %} active {% endif %}" aria-current="page" href="{% url 'home:asthkoot_table' %}">Asthkoot Table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:match_making' %}">Match Making</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/asthakoot.html
{% extends 'base.html' %} {% block content %}

<div class="container text-center">
    <h1 class="text-center mt-5">Asthkoot Table</h1>
    <hr />
    {{asthkootdf|safe}}
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>PS Astro Match | Home Page</title>
        <!-- Link to Bootstrap 5 CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
        <link rel="stylesheet" type="text/css" href="{% static 'custom/myStyle.css' %}" />
    </head>
    <body>
        {% include '_navbar.html' %}

        {% block content %}{% endblock %}

        <!-- Link to jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

        <!-- Link to Bootstrap 5 JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        {% comment %} Custom ----- {% endcomment %}
        <script src="{% static 'custom/myjs.js' %}"></script>
    </body>
</html>

templates/components/form.html
<form method="post" action="{% url 'home:get_astrology' %}"">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4 mb-3">
            <label for="dob" class="form-label">Date of Birth:</label>
            <input type="date" class="form-control" id="dob" name="dob" value="1995-05-27" required />
        </div>
        <div class="col-md-4 mb-3">
            <label for="tob" class="form-label">Time of Birth:</label>
            <input type="time" class="form-control" id="tob" name="tob" value="22:35" required />
        </div>
        <div class="col-md-4 mb-3">
            <label for="timezone" class="form-label">UTC Timezone:</label>
            <input type="text" class="form-control" id="timezone" name="timezone" value="+05:30" required />
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

templates/components/matchMakingForm.html
<form method="post" action="{% url 'home:match_making' %}">
    {% csrf_token %}
    <div class="row">
        <h3 class="txt_h3">Male</h3>
        <div class="col-md-4 mb-3">
            <label for="m_dob" class="form-label">Date of Birth:</label>
            <input type="date" class="form-control" id="m_dob" name="m_dob" {% if m_dob %} value="{{m_dob}}" {% else %} value="1995-05-27" {% endif %} required />
        </div>
        <div class="col-md-4 mb-3">
            <label for="m_tob" class="form-label">Time of Birth:</label>
            <input type="time" class="form-control" id="m_tob" name="m_tob" {% if m_tob %} value="{{m_tob}}" {% else %} value="22:35" {% endif %} required />
        </div>
        <div class="col-md-4 mb-3">
            <label for="m_timezone" class="form-label">UTC Timezone:</label>
            <input type="text" class="form-control" id="m_timezone" name="m_timezone" {% if m_tz %} value="{{m_tz}}" {% else %} value="+05:30" {% endif %} required />
        </div>
    </div>
    <div class="row">
        <h3 class="txt_h3">Female</h3>
        <div class="col-md-4 mb-3">
            <label for="f_dob" class="form-label">Date of Birth:</label>
            <input type="date" class="form-control" id="f_dob" name="f_dob" {% if f_dob %} value="{{f_dob}}" {% else %} value="1995-05-27" {% endif %} required />
        </div>
        <div class="col-md-4 mb-3">
            <label for="f_tob" class="form-label">Time of Birth:</label>
            <input type="time" class="form-control" id="f_tob" name="f_tob" {% if f_tob %} value="{{f_tob}}" {% else %} value="22:35" {% endif %} required />
        </div>
        <div class="col-md-4 mb-3">
            <label for="f_timezone" class="form-label">UTC Timezone:</label>
            <input type="text" class="form-control" id="f_timezone" name="f_timezone" {% if f_tz %} value="{{f_tz}}" {% else %} value="+05:30" {% endif %} required />
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

templates/index.html
{% extends 'base.html' %} {% block content %}

<div class="container">
    <h1 class="text-center mt-5">Enter Your Information</h1>
    <hr />
    {% include 'components/form.html' %}
    <hr />
</div>

<div class="container text-center">
    {{moondf|safe}}
</div>

{% endblock %}

templates/matchmaking.html
{% extends 'base.html' %} {% block content %}

<div class="container">
    <h1 class="text-center mt-5">Enter Your Information</h1>
    <hr />
    {% include 'components/matchMakingForm.html' %}
    <hr />
    {% if male_moondf %}
    <h3 class="text-center my-3">Male Moon Information</h3>
    <div class="container text-center">{{male_moondf|safe}}</div>
    <hr />
    {% endif %}

    <!--This is a comment. Comments are not displayed in the browser-->
    {% if female_moondf %}
    <h3 class="text-center my-3">Female Moon Information</h3>
    <div class="container text-center">{{female_moondf|safe}}</div>
    <hr />
    {% endif %}

    <!--This is a comment. Comments are not displayed in the browser-->
    {% if match_df %}
    <h3 class="text-center my-3">Match Making Results</h3>
    <div class="container text-center">{{match_df|safe}}</div>
    <hr />
    {% endif %}

    <!--This is a comment. Comments are not displayed in the browser-->
    {% if total_points %}
    <h2 class="text-center my-3">Total Points = {{total_points}}</h2>
    {% endif %}
</div>

<!--This is a comment. Comments are not displayed in the browser-->
{% endblock %}